feat: import submodule addition (#269)
* feat: import submodule addition

* update CI workflow

* remove codecov workflow, change CI workflow to have merge diff lines

* modify CI workflow

* fix tests

* fix tests

* fix tests

* add tests

* fix flake

* increase cov

* fix comments

* update submodule

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -10,21 +10,40 @@ jobs:
     environment: CI Environment
     steps:
       - uses: actions/checkout@v2 
+        with:
+          submodules: 'recursive'
+
       - name: Bring up Services and Run Tests
         run: |
           docker compose -f docker-compose-pipeline.yml build
           docker compose -f docker-compose-pipeline.yml up -d
-          docker compose -f docker-compose-pipeline.yml exec -T api pytest tests/ --cov --junit-xml=test-reports/report.xml --cov-report=xml --cov-fail-under=70          
+          docker compose -f docker-compose-pipeline.yml exec -T api pytest tests/ --cov --junit-xml=test-reports/report.xml --cov-report=xml --cov-report=term-missing --cov-fail-under=70 | tee pytest-coverage.txt
           echo "STATUS=$(cat pytest-coverage.txt | grep 'Required test' | awk '{ print $1 }')" >> $GITHUB_ENV
           echo "FAILED=$(cat test-reports/report.xml | awk -F'=' '{print $5}' | awk -F' ' '{gsub(/"/, "", $1); print $1}')" >> $GITHUB_ENV
-      - name: Upload coverage reports to Codecov with GitHub Action
-        uses: codecov/codecov-action@v3
+
       - name: Pytest coverage comment
         uses: MishaKav/pytest-coverage-comment@main
         if: ${{ always() && github.ref != 'refs/heads/master' }}
         with:
           create-new-comment: true
+          pytest-coverage-path: ./pytest-coverage.txt
           junitxml-path: ./test-reports/report.xml
+
+      - name: Perform coverage check
+        shell: bash
+        run: |
+          set -o pipefail
+          python -m pip install diff-cover
+
+          git fetch origin master --depth=1
+          diff-cover coverage.xml --compare-branch=origin/master --diff-range-notation .. --fail-under=70 > result.txt 2>&1 || echo "diff-cover failed or no changes detected" > result.txt
+
+      - name: Comment coverage check
+        if: always()
+        uses: thollander/actions-comment-pull-request@v2
+        with:
+          filePath: result.txt
+
       - name: Evaluate Coverage
         if: ${{ (env.STATUS == 'FAIL') || (env.FAILED > 0) }}
         run: exit 1
